---
apiVersion: v1
kind: Service
metadata:
  name: peer-service
spec:
  selector:
    app: peer-service
  ports:
  - port: 80
    targetPort: 80
    name: "http"
  - port: 443
    targetPort: 443
    name: "https"