apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: blueprintstore
  namespace: default
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    secretKeyRef:
      name: blueprintstore
      key: hostDomain
  - name: username
    secretKeyRef:
      name: blueprintstore
      key: username
  - name: password
    secretKeyRef:
      name: blueprintstore
      key: key
  - name: params
    secretKeyRef:
      name: blueprintstore
      key: params
  - name: database
    value: blueprintstore
  - name: collectionName
    value: DAPR
scopes:
- blueprint-service