---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: action-service
  namespace: default
  labels:
    app: action-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: action-service
  template:
    metadata:
      labels:
        app: action-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: featureconfig
        dapr.io/app-id: "action-service"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "info"
        dapr.io/app-token-secret: "app-api-token"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
        dapr.io/sidecar-readiness-probe-period-seconds: "20"
        dapr.io/http-max-request-size: "16"
        dapr.io/enable-app-health-check: "true"
        dapr.io/app-health-check-path: "/api/actions/healthz"
    spec:
      containers:
      - name: action-service
        image: {{ACR}}/action-service:latest
        env:
        - name: SERILOG__MINIMUMLEVEL
          value: {{SERILOG__MINIMUMLEVEL}}
        - name: TENANTISSUER
          value: {{TENANTISSUER}}
        - name: APP__API__TOKEN
          valueFrom:
            secretKeyRef:
              name: app-api-token
              key: token
        - name: DaprSecret
          valueFrom:
            secretKeyRef:
              name: daprsecret
              key: secret
        - name: APPINSIGHTS__INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              key: intrumentationkey
              name: appinsights
        - name: APPINSIGHTS__CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              key: connectionstring
              name: appinsights
        resources:
          requests:
            memory: "160Mi"
            cpu: "100m" 
          limits:
            memory: "600Mi"
            cpu: "750m"          
        ports:
        - containerPort: 80
        imagePullPolicy: Always