---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: default
  labels:
    app: wallet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: featureconfig
        dapr.io/app-id: "wallet-service"
        dapr.io/app-port: "8080"
        dapr.io/log-level: "info"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
        dapr.io/sidecar-readiness-probe-period-seconds: "20"
        dapr.io/app-token-secret: "app-api-token"
        dapr.io/http-max-request-size: "16"
        dapr.io/enable-app-health-check: "true"
        dapr.io/app-health-check-path: "/api/wallets/healthz"
    spec:
      containers:
      - name: wallet-service
        image: {{ACR}}/wallet-service:latest
        envFrom:
        - secretRef:
            name: app-api-token
        env:
        - name: SERILOG__MINIMUMLEVEL
          value: {{SERILOG__MINIMUMLEVEL}}
        - name: TENANTISSUER
          value: {{TENANTISSUER}}
        - name: APP__API__TOKEN
          valueFrom:
            secretKeyRef:
              name: app-api-token
              key: token
        - name: DaprSecret
          valueFrom:
            secretKeyRef:
              name: daprsecret
              key: secret
        - name: ConnectionStrings__WalletDB__ConnectionString
          valueFrom:
            secretKeyRef:
              name: walletrepository
              key: repo
        - name: APPLICATIONINSIGHTS__INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              key: intrumentationkey
              name: appinsights
        - name: APPLICATIONINSIGHTS__CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              key: connectionstring
              name: appinsights
        resources:
          requests:
            memory: "160Mi"
            cpu: "200m" 
          limits:
            memory: "640Mi"
            cpu: "750m"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
          - name: keydata
            mountPath: "/app/data"
      volumes:
        - name: keydata
          persistentVolumeClaim:
            claimName: keys-azurefile 
